# Generated by Django 5.2 on 2026-03-08 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo_inicial', models.DecimalField(decimal_places=2, help_text='Importe en efectivo con el que se abre la caja.', max_digits=10, verbose_name='Fondo inicial (€)')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('hora_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Hora apertura')),
                ('hora_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Hora cierre')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'ordering': ['-fecha', '-hora_apertura'],
            },
        ),
    ]
