# Generated by Django 5.2 on 2026-03-08 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del Cierre')),
                ('hora_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Hora del Cierre')),
                ('fondo_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fondo Inicial')),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Efectivo Esperado (Cajón)')),
                ('efectivo_retirado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Efectivo Retirado (Neto)')),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Ventas del Día')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Incidencias / Notas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero que Cierra')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha', '-hora_cierre'],
            },
        ),
    ]
