# Generated by Django 5.2 on 2026-03-08 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_cierrecaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrecaja',
            options={'ordering': ['-fecha_fin', '-hora_cierre'], 'verbose_name': 'Cierre de Caja', 'verbose_name_plural': 'Cierres de Caja'},
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha Hasta'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha Desde'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='tipo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='diario', max_length=20, verbose_name='Tipo de Cierre'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='hora_cierre',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora del Registro'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Ventas del Periodo'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Cajero'),
        ),
    ]
