# Generated by Django 5.2 on 2025-06-22 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('tpv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de factura')),
                ('serie', models.CharField(default='FAC', help_text='Serie para agrupar facturas', max_length=10, verbose_name='Serie')),
                ('tipo', models.CharField(choices=[('ordinaria', 'Factura ordinaria'), ('rectificativa', 'Factura rectificativa'), ('proforma', 'Factura proforma'), ('simplificada', 'Factura simplificada (Ticket)')], default='ordinaria', max_length=20, verbose_name='Tipo de factura')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('enviada', 'Enviada al cliente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('emisor_nombre', models.CharField(default='KUDEA TPV', max_length=255, verbose_name='Nombre emisor')),
                ('emisor_nif', models.CharField(default='', max_length=20, verbose_name='NIF/CIF emisor')),
                ('emisor_direccion', models.TextField(default='', verbose_name='Dirección emisor')),
                ('emisor_codigo_postal', models.CharField(default='', max_length=10, verbose_name='CP emisor')),
                ('emisor_ciudad', models.CharField(default='', max_length=100, verbose_name='Ciudad emisor')),
                ('emisor_provincia', models.CharField(default='', max_length=100, verbose_name='Provincia emisor')),
                ('emisor_pais', models.CharField(default='España', max_length=100, verbose_name='País emisor')),
                ('emisor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email emisor')),
                ('emisor_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono emisor')),
                ('emisor_registro_mercantil', models.TextField(blank=True, verbose_name='Registro mercantil')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cliente_apellidos', models.CharField(blank=True, max_length=100, verbose_name='Apellidos')),
                ('cliente_empresa', models.CharField(blank=True, max_length=255, verbose_name='Nombre de empresa')),
                ('cliente_nif', models.CharField(blank=True, max_length=20, verbose_name='NIF/CIF')),
                ('cliente_direccion', models.TextField(verbose_name='Dirección')),
                ('cliente_ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('cliente_provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('cliente_pais', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('cliente_codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('cliente_tipo', models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa'), ('autonomo', 'Autónomo'), ('extranjero', 'Extranjero')], default='particular', max_length=20, verbose_name='Tipo cliente')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento global')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Base imponible')),
                ('iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='IVA (%)')),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total IVA')),
                ('recargo_equivalencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='RE (%)')),
                ('total_recargo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total RE')),
                ('irpf', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IRPF (%)')),
                ('total_irpf', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total IRPF')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('domiciliacion', 'Domiciliación'), ('contrareembolso', 'Contrareembolso'), ('bitcoin', 'Bitcoin/Cripto')], default='efectivo', max_length=20, verbose_name='Método de pago')),
                ('condiciones_pago', models.CharField(blank=True, max_length=255, verbose_name='Condiciones de pago')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, verbose_name='Cuenta bancaria (IBAN)')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('enviada', models.BooleanField(default=False, verbose_name='¿Enviada al cliente?')),
                ('forma_envio', models.CharField(blank=True, max_length=100, verbose_name='Forma de envío')),
                ('tracking_envio', models.CharField(blank=True, max_length=100, verbose_name='Nº seguimiento envío')),
                ('leyenda_factura', models.TextField(blank=True, default='Factura conforme a la normativa vigente', verbose_name='Leyenda legal')),
                ('motivo_rectificacion', models.TextField(blank=True, verbose_name='Motivo rectificación')),
                ('exportacion', models.BooleanField(default=False, verbose_name='¿Exportación?')),
                ('exenta_iva', models.BooleanField(default=False, verbose_name='¿Exenta de IVA?')),
                ('motivo_exencion', models.CharField(blank=True, max_length=100, verbose_name='Motivo exención')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('modificada_en', models.DateTimeField(auto_now=True)),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('id_externo', models.CharField(blank=True, max_length=100, verbose_name='ID sistema externo')),
                ('sincronizado_con_contabilidad', models.BooleanField(default=False, verbose_name='Sincronizado con contabilidad')),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha sincronización')),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='tpv.comanda', verbose_name='Comanda asociada')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('factura_rectificada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectificaciones', to='invoice.factura', verbose_name='Factura rectificada')),
                ('modificada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificada por')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(default='ud.', max_length=20, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('tipo_iva', models.DecimalField(choices=[(21.0, '21% General'), (10.0, '10% Reducido'), (4.0, '4% Superreducido'), (0.0, '0% Exento')], decimal_places=2, default=21.0, max_digits=4, verbose_name='Tipo IVA')),
                ('total_bruto', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total bruto')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='invoice_fac_numero_c1d945_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente_nif'], name='invoice_fac_cliente_6a32aa_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='invoice_fac_fecha_e_ce16ca_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='invoice_fac_estado_be1278_idx'),
        ),
    ]
