# Generated by Django 5.2 on 2025-04-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='support/archivos/'),
        ),
    ]
