# Generated by Django 5.2 on 2026-09-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0002_alter_employee_options_employee_tarifa_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, help_text='Horas trabajadas ese día (máx. 24)', max_digits=5)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notas', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_horas', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Parte de horas',
                'verbose_name_plural': 'Partes de horas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
