# Generated by Django 5.2 on 2026-03-01 18:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_cuenta_movimiento_delete_cashflowmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AddField(
            model_name='cuenta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cashflow.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(choices=[('tpv', 'TPV'), ('factura', 'Factura'), ('arqueo', 'Arqueo'), ('manual', 'Manual'), ('sistema', 'Sistema')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['origen', 'external_ref'], name='cashflow_mo_origen_cf5bed_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha'], name='cashflow_mo_fecha_758ada_idx'),
        ),
    ]
