# Generated by Django 5.2 on 2026-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_alter_cuenta_options_movimiento_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
