# Generated by Django 5.2 on 2026-03-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('ajuste', 'Ajuste')], max_length=10)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('tpv', 'TPV'), ('arqueo', 'Arqueo'), ('factura', 'Factura')], default='manual', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='CashflowMovement',
        ),
    ]
