# Generated by Django 5.2 on 2026-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_movimiento_options_cuenta_activa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('bizum', 'Bizum')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
