# Generated by Django 5.2 on 2026-03-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_cuenta_entidad_cuenta_iban_cuenta_numero_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='canal_operacion',
            field=models.CharField(choices=[('directa', 'Venta Directa'), ('suscripcion', 'Suscripción'), ('reembolso', 'Reembolso'), ('otros', 'Otros')], default='directa', max_length=20),
        ),
    ]
