# Generated by Django 5.2 on 2025-04-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tipoticket_remove_ticket_campo1_remove_ticket_campo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
