# Generated by Django 5.2 on 2025-04-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ticket_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TipoTicket',
        ),
    ]
