# Generated by Django 5.2 on 2026-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comunicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontpv',
            name='pin_apertura',
            field=models.CharField(default='1234', max_length=4, verbose_name='PIN de apertura de caja'),
        ),
    ]
