# Generated by Django 5.2 on 2025-06-22 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('qr_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('nfc_uid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('nif', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_seguridad_social', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('movil', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('es_administrador', models.BooleanField(default=False)),
                ('puede_realizar_salidas', models.BooleanField(default=False)),
                ('puede_cambiar_fecha_hora', models.BooleanField(default=False)),
                ('puede_modificar_ventas', models.BooleanField(default=False)),
                ('puede_cambiar_subtotales', models.BooleanField(default=False)),
                ('puede_cambiar_tarifa', models.BooleanField(default=False)),
                ('esta_de_baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
