# Generated by Django 5.2 on 2025-06-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('servida', 'Servida'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('movil', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50)),
                ('es_administrador', models.BooleanField(default=False)),
                ('puede_realizar_salidas', models.BooleanField(default=False)),
                ('puede_cambiar_fecha_hora', models.BooleanField(default=False)),
                ('puede_modificar_ventas', models.BooleanField(default=False)),
                ('puede_cambiar_subtotales', models.BooleanField(default=False)),
                ('puede_cambiar_tarifa', models.BooleanField(default=False)),
                ('esta_de_baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('esperando', 'Esperando pedido')], default='libre', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tpv.comanda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='tpv.mesa'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tpv.comanda')),
            ],
        ),
    ]
