# Generated by Django 5.2 on 2026-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(choices=[('21.00', '21%'), ('15.00', '15%'), ('10.00', '10%'), ('4.00', '4%'), ('0.00', '0% (Exento)')], decimal_places=2, default='21.00', max_digits=5),
        ),
    ]
