# Generated by Django 5.2 on 2025-08-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('stock', '0002_alter_movement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterField(
            model_name='movement',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='product.producto'),
        ),
    ]
