# Generated by Django 5.2 on 2026-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionfiscal',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AddField(
            model_name='configuracionfiscal',
            name='fondo_caja_defecto',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Fondo de Caja (Defecto)'),
        ),
    ]
