# Generated by Django 5.2 on 2026-05-02 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producto_porcentaje_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(choices=[(Decimal('21.00'), '21%'), (Decimal('15.00'), '15%'), (Decimal('10.00'), '10%'), (Decimal('4.00'), '4%'), (Decimal('0.00'), '0% (Exento)')], decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
    ]
