# Generated by Django 5.2 on 2026-06-28 18:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_producto_porcentaje_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
