# Generated by Django 5.2 on 2026-09-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_categoria_porcentaje_iva'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='purchases.proveedor', verbose_name='Proveedor habitual'),
        ),
    ]
