# Generated by Django 5.2 on 2026-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración General', max_length=100)),
                ('iva_general', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuración Fiscal',
                'verbose_name_plural': 'Configuración Fiscal',
            },
        ),
    ]
