# Generated by Django 5.2 on 2026-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_configuracionfiscal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfiscal',
            name='iva_general',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
