# Generated by Django 5.2 on 2026-06-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_alter_cierrecaja_options_cierrecaja_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la caja')),
                ('pin', models.CharField(default='1234', max_length=4, verbose_name='PIN de apertura')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='cash.caja', verbose_name='Caja'),
        ),
    ]
