# Generated by Django 5.2 on 2026-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_caja_aperturacaja_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='predeterminada',
            field=models.BooleanField(default=False, verbose_name='Caja por defecto'),
        ),
    ]
