# Generated by Django 5.2 on 2026-06-28 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_caja_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='cash.caja', verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='aperturacaja',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='abierta', max_length=10),
        ),
    ]
