# Generated by Django 5.2 on 2026-05-03 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_venta_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('visto_por', models.ManyToManyField(blank=True, related_name='comunicaciones_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
