# Generated by Django 5.2 on 2026-06-28 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_configuraciontpv_pin_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontpv',
            name='iva_por_defecto',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
