# Generated by Django 5.2 on 2026-07-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_configuraciontpv_iva_por_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontpv',
            name='moneda',
            field=models.CharField(default='ARS', max_length=10),
        ),
    ]
