# Generated by Django 5.2 on 2026-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_0008_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontpv',
            name='moneda',
            field=models.CharField(default='C$', max_length=10),
        ),
    ]
