# Generated by Django 5.2 on 2026-09-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cliente_options_cliente_creado_en_and_more'),
        ('home', '0012_venta_subtotal_base_imponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='customer.cliente', verbose_name='Cliente'),
        ),
    ]
