# Generated by Django 5.2 on 2025-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
